### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ImagicalGamer** [ImagicalGamer/EconomyPlus#3]
- [x] Finish Language Translation

- [x] Add base commands

- [x] Add better API

- [x] Add shop

- [x] Add sell shop

- [ ] Auction Base

- [x] Permission Shop

**Comment by SoyPro** [comment]
and sell ?

**Comment by ImagicalGamer** [comment]
It has a sign shop.

**Comment by ImagicalGamer** [comment]
I will add sell shop

**Comment by ImagicalGamer** [comment]
@SoyPro Can you test shops and sell to make sure it's fully working please?

**Comment by SoyPro** [comment]
yes

**Comment by SoyPro** [comment]
console show this:
[06:43:04] [Server thread/INFO]: 

		   PocketMine-iTX Genisys is a fork of PocketMine-MP, made by iTX Technologies LLC.
		   Version: 1.2dev-640
		   Target client Version: v0.15.0 alpha
		   Latest source code is available at https://github.com/iTXTech/Genisys
		   Donate link: http://pl.zxda.net/plugins/203.html
		

[06:43:04] [Server thread/INFO]: Loading pocketmine.yml...
[06:43:04] [Server thread/INFO]: Loading genisys.yml...
[06:43:05] [Server thread/INFO]: Loading server properties...
[06:43:05] [Server thread/INFO]: Selected English (eng) as the base language
[06:43:05] [Server thread/INFO]: Starting Minecraft: PE server version v0.15.0 alpha
[06:43:05] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[06:43:05] [Server thread/INFO]: This server is running Genisys version 1.2dev-640 "Kyrios" (API 2.0.0)
[06:43:05] [Server thread/INFO]: Genisys is distributed under the GPL License version 3 and later
[06:43:07] [Server thread/INFO]: Loading ChatToolsPro v1
[06:43:07] [Server thread/INFO]: Loading superBAR v1.5.1
[06:43:07] [Server thread/INFO]: Loading ServerAuth v2.13
[06:43:07] [Server thread/INFO]: Loading ParticlesPlus v0.0.2
[06:43:07] [Server thread/INFO]: Loading SClearLagg vBeta_0.2
[06:43:07] [Server thread/INFO]: Loading EconomyAPI v2.0.9
[06:43:07] [Server thread/INFO]: Loading AntiSpam v1.2
[06:43:07] [Server thread/INFO]: Loading EconomyJob v2.0.4
[06:43:07] [Server thread/INFO]: Loading NoAdvertisingPE v1.0.1
[06:43:07] [Server thread/INFO]: Loading MagicServer v1.0.1
[06:43:07] [Server thread/INFO]: Loading DevTools v1.11.0
[06:43:07] [Server thread/INFO]: Loading BanItem v2.2
[06:43:07] [Server thread/INFO]: Loading CombatLogger v1.2.0
[06:43:07] [Server thread/INFO]: Loading MineReset v2.1
[06:43:07] [Server thread/INFO]: Loading Broadcaster v1.16
[06:43:07] [Server thread/INFO]: Loading Slapper v1.2.9.7
[06:43:07] [Server thread/INFO]: Loading iProtector v3.1b
[06:43:07] [Server thread/INFO]: Loading EconomySell v2.0.7
[06:43:07] [Server thread/INFO]: Loading EconomyShop v2.0.7
[06:43:07] [Server thread/INFO]: Loading PurePerms v1.3.7
[06:43:07] [Server thread/NOTICE]: PurePerms by 64FF00 & ProjectInfinity! #LEET.CC

  888  888    .d8888b.      d8888  8888888888 8888888888 .d8888b.   .d8888b. 
  888  888   d88P  Y88b    d8P888  888        888       d88P  Y88b d88P  Y88b
888888888888 888          d8P 888  888        888       888    888 888    888
  888  888   888d888b.   d8P  888  8888888    8888888   888    888 888    888
  888  888   888P "Y88b d88   888  888        888       888    888 888    888
888888888888 888    888 8888888888 888        888       888    888 888    888
  888  888   Y88b  d88P       888  888        888       Y88b  d88P Y88b  d88P
  888  888    "Y8888P"        888  888        888        "Y8888P"   "Y8888P" 

[06:43:07] [Server thread/INFO]: [PurePerms] Setting default language to 'en'
[06:43:07] [Server thread/NOTICE]: [PurePerms] Multiworld support is currently disabled.
[06:43:07] [Server thread/NOTICE]: [PurePerms] Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions!
[06:43:07] [Server thread/INFO]: Loading TimeCommander v2.1
[06:43:07] [Server thread/INFO]: Loading zhManagedKits v2.0.2
[06:43:07] [Server thread/INFO]: Loading JQDSounds v2.1
[06:43:07] [Server thread/INFO]: Loading source plugin EconomyPlus v0.1.4
[06:43:07] [Server thread/INFO]: Loading PureChat v1.4.0
[06:43:07] [Server thread/INFO]: Loading SimpleWarp v2.1.1
[06:43:07] [Server thread/INFO]: Enabling ServerAuth v2.13
[06:43:07] [Server thread/INFO]: Enabling SClearLagg vBeta_0.2
[06:43:07] [Server thread/INFO]: [SClearLagg] SClearLagg V_Beta_0.2 от Sergey Dertanз загружен
[06:43:07] [Server thread/INFO]: Enabling AntiSpam v1.2
[06:43:07] [Server thread/INFO]: Enabling DevTools v1.11.0
[06:43:07] [Server thread/ERROR]: Could not load plugin 'EconomyPlus': plugin exists
[06:43:07] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[06:43:07] [Server thread/INFO]: Enabling Broadcaster v1.16
[06:43:07] [Server thread/INFO]: Preparing level "world"
[06:43:07] [Server thread/INFO]: Enabling ChatToolsPro v1
[06:43:07] [Server thread/INFO]: [ChatToolsPro] ChatToolsPro by paetti loaded. Coded by paetti. Instagram: xPaetti Kik: Oupsay
[06:43:07] [Server thread/INFO]: Enabling superBAR v1.5.1
[06:43:07] [Server thread/INFO]: [superBAR] superBAR will be enabled after the complete server load...
[06:43:07] [Server thread/INFO]: Enabling ParticlesPlus v0.0.2
[06:43:07] [Server thread/INFO]: Enabling EconomyAPI v2.0.9
[06:43:07] [Server thread/NOTICE]: [EconomyAPI] Auto save has been set to interval : 10 min(s)
[06:43:07] [Server thread/INFO]: [EconomyAPI] Checking for updates... It may be take some while.
[06:43:13] [Server thread/NOTICE]: [EconomyAPI] 
[06:43:13] [Server thread/INFO]: Enabling EconomyJob v2.0.4
[06:43:13] [Server thread/INFO]: Enabling NoAdvertisingPE v1.0.1
[06:43:13] [Server thread/INFO]: NoAdvertisingPE is ready!
[06:43:13] [Server thread/INFO]: Enabling MagicServer v1.0.1
[06:43:13] [Server thread/INFO]: [MagicServer] MagicServer ENABLED!
[06:43:13] [Server thread/INFO]: [MagicServer] Running version 1.0.0...
[06:43:13] [Server thread/INFO]: Enabling BanItem v2.2
[06:43:13] [Server thread/INFO]: Enabling CombatLogger v1.2.0
[06:43:13] [Server thread/INFO]: CombatLogger enabled
[06:43:13] [Server thread/INFO]: Enabling MineReset v2.1
[06:43:13] [Server thread/INFO]: Enabling Slapper v1.2.9.7
[06:43:13] [Server thread/INFO]: Enabling iProtector v3.1b
[06:43:13] [Server thread/INFO]: Enabling EconomySell v2.0.7
[06:43:13] [Server thread/INFO]: Enabling EconomyShop v2.0.7
[06:43:13] [Server thread/INFO]: Enabling PurePerms v1.3.7
[06:43:13] [Server thread/NOTICE]: [PurePerms] Set data provider to YAMLv1.
[06:43:13] [Server thread/INFO]: Enabling TimeCommander v2.1
[06:43:13] [Server thread/INFO]: Enabling zhManagedKits v2.0.2
[06:43:13] [Server thread/INFO]: [zhManagedKits] Checking configuration:
[06:43:13] [Server thread/INFO]: [zhManagedKits] ... done
[06:43:13] [Server thread/INFO]: [zhManagedKits] Current translation is the last available
[06:43:13] [Server thread/INFO]: [zhManagedKits] Loading translation: eng
[06:43:13] [Server thread/INFO]: [zhManagedKits] Initializing:
[06:43:13] [Server thread/INFO]: [zhManagedKits] ... total kits: 8
[06:43:13] [Server thread/INFO]: [zhManagedKits] Economy API support is enabled (onebone)
[06:43:13] [Server thread/INFO]: [zhManagedKits] Default kit feature is enabled
[06:43:13] [Server thread/INFO]: [zhManagedKits] Kit Default will be used as default
[06:43:13] [Server thread/INFO]: [zhManagedKits] Kit signs feature is enabled
[06:43:13] [Server thread/INFO]: Enabling JQDSounds v2.1
[06:43:13] [Server thread/INFO]: [JQDSounds] Activated!
[06:43:13] [Server thread/INFO]: Enabling EconomyPlus v0.1.4

Warning: file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in /storage/emulated/0/PocketMine/plugins/EconomyPlus-master/src/EconomyPlus/Main.php on line 119

Warning: file_get_contents(https://raw.githubusercontent.com/ImagicalGamer/EconomyPlus/master/resources/version): failed to open stream: No such file or directory in /storage/emulated/0/PocketMine/plugins/EconomyPlus-master/src/EconomyPlus/Main.php on line 119
[06:43:13] [Server thread/INFO]: [EconomyPlus] No Updates Found! Your using the latest version of EconomyPlus!
[06:43:13] [Server thread/INFO]: [EconomyPlus] EconomyPlus v0.1.4 Enabled!
[06:43:13] [Server thread/INFO]: Enabling PureChat v1.4.0
[06:43:13] [Server thread/NOTICE]: [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support.
[06:43:13] [Server thread/INFO]: Enabling SimpleWarp v2.1.1
[06:43:15] [Server thread/INFO]: Starting GS4 status listener
[06:43:15] [Server thread/INFO]: Setting query port to 19132
[06:43:15] [Server thread/INFO]: Query running on 0.0.0.0:19132
[06:43:15] [Server thread/INFO]: Default game type: Survival Mode
[06:43:15] [Server thread/INFO]: Done (11.218s)! For help, type "help" or "?"
[06:43:15] [Server thread/INFO]: [ClearLag] Warning groud items will be removed in 60 seconds!
[06:43:16] [Server thread/INFO]: [Anuncio] Welcome to this server!
[06:43:16] [Server thread/INFO]: [ClearLag] removed 0 entities!
[06:43:16] [Server thread/INFO]: [superBAR] superBAR loading...
[06:43:16] [Server thread/INFO]: [superBAR] EconomyAPI OK!
[06:43:16] [Server thread/INFO]: [superBAR] PurePerms OK!
[06:43:16] [Server thread/INFO]: [superBAR] superBAR by FaigerSYS enabled!
[06:46:16] [Server thread/INFO]: [INFO]: Invit your friends to this server!
[06:47:15] [Server thread/INFO]: [ClearLag] Warinig grond items will be removed in 60 seconds!

**Comment by SoyPro** [comment]
[06:43:04] [Server thread/INFO]: 

		   PocketMine-iTX Genisys is a fork of PocketMine-MP, made by iTX Technologies LLC.
		   Version: 1.2dev-640
		   Target client Version: v0.15.0 alpha
		   Latest source code is available at https://github.com/iTXTech/Genisys
		   Donate link: http://pl.zxda.net/plugins/203.html
		

[06:43:04] [Server thread/INFO]: Loading pocketmine.yml...
[06:43:04] [Server thread/INFO]: Loading genisys.yml...
[06:43:05] [Server thread/INFO]: Loading server properties...
[06:43:05] [Server thread/INFO]: Selected English (eng) as the base language
[06:43:05] [Server thread/INFO]: Starting Minecraft: PE server version v0.15.0 alpha
[06:43:05] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[06:43:05] [Server thread/INFO]: This server is running Genisys version 1.2dev-640 "Kyrios" (API 2.0.0)
[06:43:05] [Server thread/INFO]: Genisys is distributed under the GPL License version 3 and later
[06:43:07] [Server thread/INFO]: Loading ChatToolsPro v1
[06:43:07] [Server thread/INFO]: Loading superBAR v1.5.1
[06:43:07] [Server thread/INFO]: Loading ServerAuth v2.13
[06:43:07] [Server thread/INFO]: Loading ParticlesPlus v0.0.2
[06:43:07] [Server thread/INFO]: Loading SClearLagg vBeta_0.2
[06:43:07] [Server thread/INFO]: Loading EconomyAPI v2.0.9
[06:43:07] [Server thread/INFO]: Loading AntiSpam v1.2
[06:43:07] [Server thread/INFO]: Loading EconomyJob v2.0.4
[06:43:07] [Server thread/INFO]: Loading NoAdvertisingPE v1.0.1
[06:43:07] [Server thread/INFO]: Loading MagicServer v1.0.1
[06:43:07] [Server thread/INFO]: Loading DevTools v1.11.0
[06:43:07] [Server thread/INFO]: Loading BanItem v2.2
[06:43:07] [Server thread/INFO]: Loading CombatLogger v1.2.0
[06:43:07] [Server thread/INFO]: Loading MineReset v2.1
[06:43:07] [Server thread/INFO]: Loading Broadcaster v1.16
[06:43:07] [Server thread/INFO]: Loading Slapper v1.2.9.7
[06:43:07] [Server thread/INFO]: Loading iProtector v3.1b
[06:43:07] [Server thread/INFO]: Loading EconomySell v2.0.7
[06:43:07] [Server thread/INFO]: Loading EconomyShop v2.0.7
[06:43:07] [Server thread/INFO]: Loading PurePerms v1.3.7
[06:43:07] [Server thread/NOTICE]: PurePerms by 64FF00 & ProjectInfinity! #LEET.CC

  888  888    .d8888b.      d8888  8888888888 8888888888 .d8888b.   .d8888b. 
  888  888   d88P  Y88b    d8P888  888        888       d88P  Y88b d88P  Y88b
888888888888 888          d8P 888  888        888       888    888 888    888
  888  888   888d888b.   d8P  888  8888888    8888888   888    888 888    888
  888  888   888P "Y88b d88   888  888        888       888    888 888    888
888888888888 888    888 8888888888 888        888       888    888 888    888
  888  888   Y88b  d88P       888  888        888       Y88b  d88P Y88b  d88P
  888  888    "Y8888P"        888  888        888        "Y8888P"   "Y8888P" 

[06:43:07] [Server thread/INFO]: [PurePerms] Setting default language to 'en'
[06:43:07] [Server thread/NOTICE]: [PurePerms] Multiworld support is currently disabled.
[06:43:07] [Server thread/NOTICE]: [PurePerms] Don't forget to set enable-multiworld-perms option in config.yml to true if you want to use per-world permissions!
[06:43:07] [Server thread/INFO]: Loading TimeCommander v2.1
[06:43:07] [Server thread/INFO]: Loading zhManagedKits v2.0.2
[06:43:07] [Server thread/INFO]: Loading JQDSounds v2.1
[06:43:07] [Server thread/INFO]: Loading source plugin EconomyPlus v0.1.4
[06:43:07] [Server thread/INFO]: Loading PureChat v1.4.0
[06:43:07] [Server thread/INFO]: Loading SimpleWarp v2.1.1
[06:43:07] [Server thread/INFO]: Enabling ServerAuth v2.13
[06:43:07] [Server thread/INFO]: Enabling SClearLagg vBeta_0.2
[06:43:07] [Server thread/INFO]: [SClearLagg] SClearLagg V_Beta_0.2 от Sergey Dertanз загружен
[06:43:07] [Server thread/INFO]: Enabling AntiSpam v1.2
[06:43:07] [Server thread/INFO]: Enabling DevTools v1.11.0
[06:43:07] [Server thread/ERROR]: Could not load plugin 'EconomyPlus': plugin exists
[06:43:07] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[06:43:07] [Server thread/INFO]: Enabling Broadcaster v1.16
[06:43:07] [Server thread/INFO]: Preparing level "world"
[06:43:07] [Server thread/INFO]: Enabling ChatToolsPro v1
[06:43:07] [Server thread/INFO]: [ChatToolsPro] ChatToolsPro by paetti loaded. Coded by paetti. Instagram: xPaetti Kik: Oupsay
[06:43:07] [Server thread/INFO]: Enabling superBAR v1.5.1
[06:43:07] [Server thread/INFO]: [superBAR] superBAR will be enabled after the complete server load...
[06:43:07] [Server thread/INFO]: Enabling ParticlesPlus v0.0.2
[06:43:07] [Server thread/INFO]: Enabling EconomyAPI v2.0.9
[06:43:07] [Server thread/NOTICE]: [EconomyAPI] Auto save has been set to interval : 10 min(s)
[06:43:07] [Server thread/INFO]: [EconomyAPI] Checking for updates... It may be take some while.
[06:43:13] [Server thread/NOTICE]: [EconomyAPI] 
[06:43:13] [Server thread/INFO]: Enabling EconomyJob v2.0.4
[06:43:13] [Server thread/INFO]: Enabling NoAdvertisingPE v1.0.1
[06:43:13] [Server thread/INFO]: NoAdvertisingPE is ready!
[06:43:13] [Server thread/INFO]: Enabling MagicServer v1.0.1
[06:43:13] [Server thread/INFO]: [MagicServer] MagicServer ENABLED!
[06:43:13] [Server thread/INFO]: [MagicServer] Running version 1.0.0...
[06:43:13] [Server thread/INFO]: Enabling BanItem v2.2
[06:43:13] [Server thread/INFO]: Enabling CombatLogger v1.2.0
[06:43:13] [Server thread/INFO]: CombatLogger enabled
[06:43:13] [Server thread/INFO]: Enabling MineReset v2.1
[06:43:13] [Server thread/INFO]: Enabling Slapper v1.2.9.7
[06:43:13] [Server thread/INFO]: Enabling iProtector v3.1b
[06:43:13] [Server thread/INFO]: Enabling EconomySell v2.0.7
[06:43:13] [Server thread/INFO]: Enabling EconomyShop v2.0.7
[06:43:13] [Server thread/INFO]: Enabling PurePerms v1.3.7
[06:43:13] [Server thread/NOTICE]: [PurePerms] Set data provider to YAMLv1.
[06:43:13] [Server thread/INFO]: Enabling TimeCommander v2.1
[06:43:13] [Server thread/INFO]: Enabling zhManagedKits v2.0.2
[06:43:13] [Server thread/INFO]: [zhManagedKits] Checking configuration:
[06:43:13] [Server thread/INFO]: [zhManagedKits] ... done
[06:43:13] [Server thread/INFO]: [zhManagedKits] Current translation is the last available
[06:43:13] [Server thread/INFO]: [zhManagedKits] Loading translation: eng
[06:43:13] [Server thread/INFO]: [zhManagedKits] Initializing:
[06:43:13] [Server thread/INFO]: [zhManagedKits] ... total kits: 8
[06:43:13] [Server thread/INFO]: [zhManagedKits] Economy API support is enabled (onebone)
[06:43:13] [Server thread/INFO]: [zhManagedKits] Default kit feature is enabled
[06:43:13] [Server thread/INFO]: [zhManagedKits] Kit Default will be used as default
[06:43:13] [Server thread/INFO]: [zhManagedKits] Kit signs feature is enabled
[06:43:13] [Server thread/INFO]: Enabling JQDSounds v2.1
[06:43:13] [Server thread/INFO]: [JQDSounds] Activated!
[06:43:13] [Server thread/INFO]: Enabling EconomyPlus v0.1.4

Warning: file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in /storage/emulated/0/PocketMine/plugins/EconomyPlus-master/src/EconomyPlus/Main.php on line 119

Warning: file_get_contents(https://raw.githubusercontent.com/ImagicalGamer/EconomyPlus/master/resources/version): failed to open stream: No such file or directory in /storage/emulated/0/PocketMine/plugins/EconomyPlus-master/src/EconomyPlus/Main.php on line 119
[06:43:13] [Server thread/INFO]: [EconomyPlus] No Updates Found! Your using the latest version of EconomyPlus!
[06:43:13] [Server thread/INFO]: [EconomyPlus] EconomyPlus v0.1.4 Enabled!
[06:43:13] [Server thread/INFO]: Enabling PureChat v1.4.0
[06:43:13] [Server thread/NOTICE]: [PureChat] No valid factions plugin in default-factions-plugin node was found. Disabling factions plugin support.
[06:43:13] [Server thread/INFO]: Enabling SimpleWarp v2.1.1
[06:43:15] [Server thread/INFO]: Starting GS4 status listener
[06:43:15] [Server thread/INFO]: Setting query port to 19132
[06:43:15] [Server thread/INFO]: Query running on 0.0.0.0:19132
[06:43:15] [Server thread/INFO]: Default game type: Survival Mode
[06:43:15] [Server thread/INFO]: Done (11.218s)! For help, type "help" or "?"
[06:43:16] [Server thread/INFO]: [superBAR] superBAR loading...
[06:43:16] [Server thread/INFO]: [superBAR] EconomyAPI OK!
[06:43:16] [Server thread/INFO]: [superBAR] PurePerms OK!
[06:43:16] [Server thread/INFO]: [superBAR] superBAR by FaigerSYS enabled!

**Comment by ImagicalGamer** [comment]
Thats just a minor update bug.

**Comment by ImagicalGamer** [comment]
I'm working on it

**Comment by SoyPro** [comment]
ok thanks. Update in imagicalmine forums

**Comment by Thecraftdu34** [comment]
Hello, can you add PurePerm support? (It's for sell permission)

**Comment by ImagicalGamer** [comment]
@Thecraftdu34 You want me to add permissions to create shops?

**Comment by Thecraftdu34** [comment]
No, i want to create permission shop ^^ To sell permission (sorry for bad english i'm french :3)

**Comment by ImagicalGamer** [comment]
Ohh now I understand! xD I will start working on Perm Shops!

**Comment by Thecraftdu34** [comment]
Thanks ! I love u xD

**Comment by ImagicalGamer** [comment]
@Thecraftdu34 Just finished the PermissionShop! Can you test it?

**Comment by Thecraftdu34** [comment]
@ImagicalGamer Yeah, no problem. I

**Comment by Thecraftdu34** [comment]
Omg ! That works but when i've a long perm like "pocketmine.command.kick" i didn't have place :c

**Comment by ImagicalGamer** [comment]
I will make it so line 2 and 3 can have the permission!

**Comment by Thecraftdu34** [comment]
Thanks a lot to take time for me !

**Comment by ImagicalGamer** [comment]
No problem! It was a great idea!

**Comment by ImagicalGamer** [comment]
@Thecraftdu34 Now The sign format is:
`[Shop]`
`price`
`perm`
`perm`
So you can continue the permission from the 3rd line!

**Comment by Thecraftdu34** [comment]
It's work fine, no bug ! Thanks u r a great personn

**Comment by Thecraftdu34** [comment]
If you need help for french translation, tell me. :D

**Comment by ImagicalGamer** [comment]
Yes I'm starting to work on translations for messages!

**Comment by Thecraftdu34** [comment]
And you need help?

**Comment by ImagicalGamer** [comment]
Yes, can you translate [this](https://gist.github.com/ImagicalGamer/43dcb1a9cd2586ca3bac9e1c405965c6l) to French?

**Comment by Thecraftdu34** [comment]
---
INVALID-BALANCE: "Tu n'as pas assez d'argent ! " 
INVALID-PRICE: "Tu as mis un mauvais prix."
INVALID-ITEM: "Tu as mis un mauvais item."

INVALID-PERMISSION: "Tu n'as pas la permission ! "

UPDATE-FOUND: "Une nouvelle mise à jour de EconomyPlus  est disponible !"
NO-UPDATE: "Aucun mise à jour disponible, tu utilise la dernière version de EconomyPlus"
...

**Comment by ImagicalGamer** [comment]
@Thecraftdu34 What would "Invalid Amount" translate too? I forgot to add it xD

**Comment by Thecraftdu34** [comment]
"Invalid Amount" = "Mauvais montant" this message is if player make "0" to amount case?

**Comment by ImagicalGamer** [comment]
Yes

**Comment by Thecraftdu34** [comment]
Olay so it's correct

**Comment by Taki21** [comment]
Long time no see :) Need any help dude?

**Comment by ImagicalGamer** [comment]
TAKI  FAM!!!!!!!!!!!!!!!

**Comment by ImagicalGamer** [comment]
Just with language translating on [this](https://gist.github.com/ImagicalGamer/43dcb1a9cd2586ca3bac9e1c405965c6)

**Comment by Taki21** [comment]
Ok what languages?

**Comment by Taki21** [comment]
Troll google translator

**Comment by remotevase** [comment]
If you need help for translating to most languages, I can help (Tanks gogle tanslat AKA Thanks google translate)

**Comment by Thecraftdu34** [comment]
Google translate is not the better solution.

**Comment by Taki21** [comment]
well why?

**Comment by Taki21** [comment]
Well it does makes mistakes with some non common languages but... with common languages it doesnt

**Comment by ImagicalGamer** [comment]
I'm not apart of this argument xD

**Comment by iPeedroPvP** [comment]
have a bug on Sell and Shop, i buy infinit items

**Comment by ImagicalGamer** [comment]
@iPeedroPvP Any other info about this bug? Is it reducing your money when you buy a item?

**Comment by ImagicalGamer** [comment]
@Taki21 @remotevase I wanna do an auto updater Ik how but idk how I could delete the old phar and install the new one since once the old phar is deleted it can't execute the code anymore unless it was another plugin that served as the updater?

**Comment by Taki21** [comment]
i think i know what can help...
unlink() deletes file, but do u know how to get it from a website?

**Comment by Taki21** [comment]
Usage:
$file = (The Phar File);
unlink($file);

Example:
unlink("lol.phar);

or

$phar = "lol.phar"
unlink($phar);

**Comment by ImagicalGamer** [comment]
Yes Ik how to download and unlink and stuff but once I unlink the old phar it can't be used anymore and I can't enable the new phar without a reload or server restart.

**Comment by Taki21** [comment]
wow really?

**Comment by Taki21** [comment]
PHP is screwed... lately xD

**Comment by remotevase** [comment]
Yep
